PEP 639 compliance (#294)
* PEP 639 compliance

Keep the redundant Trove classifier for now, until tools such as
pip-licenses support PEP 639.

* Remove the redundant Trove classifier after all

Fixes this build error:
      flit_core.config.ConfigError: License classifiers are deprecated in favor of the license expression.
                                    Remove the 'License :: OSI Approved :: MIT License' classifier

* Bump flit version to support PEP 639