Remove the redundant Trove classifier after all
Fixes this build error:
      flit_core.config.ConfigError: License classifiers are deprecated in favor of the license expression.
                                    Remove the 'License :: OSI Approved :: MIT License' classifier